# Generated by Django 5.0.7 on 2025-08-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="title",
            field=models.CharField(max_length=255, verbose_name="شهر"),
        ),
    ]
