"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-7d651okre(hwv57m@o9wwvo#_gi_jsk$j2@8(#=qhhd6m+n3ba"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "custom_login.mybackend.ModelBackend",
]


X_FRAME_OPTIONS = "SAMEORIGIN"


# Application definition

INSTALLED_APPS = [
    "admin_interface",
    "admin_confirm",
    "colorfield",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "import_export",
    "shop.apps.ShopConfig",
    "custom_login",
    "tinymce",
    "blog",
    "rest_framework",
    "django.contrib.sitemaps",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "shop.context_processors.cart",
                "shop.context_processors.category",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "elenovastyle",
        "USER": "dev",
        "PASSWORD": "Amir@13511348",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "fa"

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_TZ = False

# Media files configuration
MEDIA_URL = "/media/"
MEDIA_ROOT = "/home/artinoga/public_html/media"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

TINYMCE_DEFAULT_CONFIG = {
    "height": 500,
    "width": "100%",
    "plugins": "advlist autolink lists link image charmap print preview hr anchor pagebreak",
    "toolbar": "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | "
    "bullist numlist outdent indent | link image",
    "image_advtab": True,
    "style_formats": [
        {
            "title": "Responsive Image",
            "block": "img",
            "classes": "responsive-image",
            "styles": {"max-width": "100%", "height": "auto"},
        },
    ],
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "custom_login.MyUser"

kavenegar_API = os.getenv("kavenegar_API")

STOCK_API_KEY = "123456789"
MANAGEMENT_API_KEY = "987654321"
UPDATE_PRICE = "a123456789"

ZARINPAL_API_REQUEST = "https://www.zarinpal.com/pg/v4/payment/request.json"
ZARINPAL_ZP_API_VERIFY = "https://www.zarinpal.com/pg/v4/payment/verify.json"
ZARINPAL_API_STARTPAY = "https://www.zarinpal.com/pg/StartPay/"
ZARINPAL_CALLBACK_URL = "http://artinogame.com/verify"
MERCHANT = os.getenv("MERCHANT")

SANDBOX = False

# Snapppay
SNAPPPAY_API_BASE = "https://api.snapppay.ir"
SNAPPPAY_CLIENT_ID = "artino-game"
SNAPPPAY_CLIENT_SECRET = "alAGzzF^W58tKVAI"
SNAPPPAY_USERNAME = "artino-game-purchase"
SNAPPPAY_PASSWORD = "0aVoKQ2tF6~iMaZ9"
SNAPPPAY_RETURN_URL = "https://artinogame.com/snapppay-result"
