# Generated by Django 5.0.7 on 2025-02-16 18:25

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('seo_title', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو')),
                ('meta', models.CharField(max_length=255, verbose_name='متا')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='لینک')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='کنونیکال')),
                ('image', models.ImageField(upload_to='image/blog', verbose_name='تصویر گالری')),
                ('content', tinymce.models.HTMLField(verbose_name='محتوا')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ ساخت')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ تغییر')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('phone_number', models.CharField(max_length=255, verbose_name='شماره تلفن')),
                ('comment', models.TextField(max_length=900, verbose_name='نظر')),
                ('approved', models.BooleanField(default=False, verbose_name='تاییده شده')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ ساخت')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost', verbose_name='بلاگ')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظر',
            },
        ),
    ]
