# Generated by Django 5.0.7 on 2025-02-16 18:25

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='عنوان مشخصه')),
            ],
            options={
                'verbose_name': 'مشخصه',
                'verbose_name_plural': 'مشخصه',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('seo_title', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو')),
                ('meta', models.CharField(max_length=255, null=True, verbose_name='توضیحات سئو')),
                ('content', tinymce.models.HTMLField(null=True, verbose_name='محتوای سئو')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/product', verbose_name='تصویر دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('code', models.CharField(max_length=255, verbose_name='کد تخفیف')),
                ('valid_from', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('valid_to', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('min_purchase', models.PositiveIntegerField(verbose_name='حداقل مبلغ کل فاکتور')),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد تخفیف')),
                ('discount_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ تخفیف')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد تخفیف',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('user_id', models.PositiveIntegerField(verbose_name='کاربر')),
                ('order_id', models.PositiveIntegerField(verbose_name='شماره سفارش')),
                ('status', models.CharField(max_length=100, verbose_name='وضعیت')),
                ('error_code', models.CharField(max_length=200, verbose_name='کد خطا')),
            ],
            options={
                'verbose_name': 'گزارش پرداختی',
                'verbose_name_plural': 'گزارش پرداختی',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255, verbose_name='ارزش مشخصه')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.attribute', verbose_name='مشخصه')),
            ],
            options={
                'verbose_name': 'ارزش مشخصه',
                'verbose_name_plural': 'ارزش مشخصه',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.IntegerField(verbose_name='مبغ کل')),
                ('status', models.CharField(blank=True, choices=[('FA', 'پرداخت ناموفق'), ('DO', 'پرداخت موفق')], max_length=2, null=True, verbose_name='وضعیت')),
                ('order_user_name', models.CharField(max_length=200, null=True, verbose_name='نام')),
                ('order_mobile', models.CharField(max_length=11, null=True, verbose_name='شماره موبایل')),
                ('order_address', models.TextField(max_length=500, null=True, verbose_name='آدرس محل سکونت')),
                ('order_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('gateway_bank_order_authority', models.CharField(max_length=50, null=True)),
                ('gateway_bank_order_ref_id', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ ساخت')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ تغییر')),
                ('order_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_login.city', verbose_name='شهر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('seo_title', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو')),
                ('meta', models.CharField(max_length=255, null=True, verbose_name='توضیحات سئو')),
                ('product_slug', models.SlugField(null=True, unique=True, verbose_name='لینک')),
                ('content', tinymce.models.HTMLField(verbose_name='محتوای سئو')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/product', verbose_name='تصویر اصلی')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='وضعیت نمایش')),
                ('content_code', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='کد محتوا')),
                ('glass', models.CharField(blank=True, choices=[('با شیشه', 'با شیشه'), ('بدون شیشه', 'بدون شیشه')], max_length=255, null=True, verbose_name='شیشه')),
                ('frame', models.CharField(blank=True, choices=[('تخت 2 در 2', 'تخت 2 در 2'), ('تخت 2 در 3', 'تخت 2 در 3'), ('هرمی 2', 'هرمی 2'), ('هرمی 3', 'هرمی 3'), ('فلز', 'فلز'), ('گرد 1 در 1', 'گرد 1 در 1'), ('تخت 3 در 3', 'تخت 3 در 3'), ('عمیق 2.5 در 4.5', 'عمیق 2.5 در 4.5'), ('تخت 3 در 2', 'تخت 3 در 2'), ('قوس دار 3.5 در 2', 'قوس دار 3.5 در 2'), ('قوس دار 4.5 در 3.5', 'قوس دار 4.5 در 3.5'), ('تخت 5 در 2', 'تخت 5 در 2'), ('معلق 5 در 4', 'معلق 5 در 4'), ('تخت 4 در 2', 'تخت 4 در 2'), ('عمیق 4 در 4', 'عمیق 4 در 4'), ('طرحدار 7 در 4', 'طرحدار 7 در 4'), ('تخت 1 در 2', 'تخت 1 در 2'), ('قوس دار با حاشیه 4 در 2.5', 'قوس دار با حاشیه 4 در 2.5')], max_length=255, null=True)),
                ('color', models.CharField(blank=True, choices=[('سفید', 'سفید'), ('مشکی', 'مشکی'), ('چوبی', 'چوبی'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('نارنجی', 'نارنجی')], max_length=255, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ ساخت')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ تغییر')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveBigIntegerField(verbose_name='تعداد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.attribute', verbose_name='مشخصه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.attributevalue', verbose_name='ارزش')),
            ],
            options={
                'verbose_name': 'مشخصه های فنی محصولات',
                'verbose_name_plural': 'مشخصه های فنی محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/product', verbose_name='تصویر گالری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر گالری محصول',
                'verbose_name_plural': 'تصویر گالری محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('width', models.CharField(max_length=255, verbose_name='عرض')),
                ('height', models.CharField(max_length=255, verbose_name='طول')),
                ('product_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد محصول')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('stock', models.PositiveIntegerField(null=True)),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تخفیف')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول به تفکیک ابعاد',
                'verbose_name_plural': 'محصول به تفکیک ابعاد',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productsize', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'آیتم سفارشات',
                'verbose_name_plural': 'آیتم سفارشات',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='shop_produc_status_295d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['content_code'], name='shop_produc_content_a2a2d7_idx'),
        ),
    ]
