# Generated by Django 5.0.7 on 2025-03-08 14:35

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('سفید', 'سفید'), ('مشکی', 'مشکی'), ('چوبی', 'چوبی'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('نارنجی', 'نارنجی'), ('خاکستری', 'خاکستری')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=tinymce.models.HTMLField(null=True, verbose_name='محتوای سئو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='لینک'),
        ),
    ]
