# Generated by Django 5.0.7 on 2025-03-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_color_alter_product_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('سفید', 'سفید'), ('مشکی', 'مشکی'), ('چوبی', 'چوبی'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('نارنجی', 'نارنجی'), ('خاکستری', 'خاکستری'), ('سبز', 'سبز')], max_length=255, null=True),
        ),
    ]
