# Generated by Django 5.0.7 on 2025-03-09 14:18

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='محتوای سئو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
    ]
