# Generated by Django 5.0.7 on 2025-04-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_content_alter_product_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_optimized',
            field=models.ImageField(blank=True, null=True, upload_to='image/product', verbose_name='تصویر لیست'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_optimized_two',
            field=models.ImageField(blank=True, null=True, upload_to='image/product', verbose_name='تصویر دوم لیست'),
        ),
    ]
