# Generated by Django 5.0.7 on 2025-04-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_image_optimized_product_image_optimized_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gateway_bank_order_ref_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
