# Generated by Django 5.0.7 on 2025-07-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_gateway_bank_order_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('snapppay', 'SnappPay'), ('zarinpal', 'Zarinpal')], default='zarinpal', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='snapppay_payment_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='snapppay_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
