# Generated by Django 5.0.7 on 2025-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_order_payment_method_order_snapppay_payment_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FA", "پرداخت ناموفق"),
                    ("DO", "پرداخت موفق"),
                    ("SC", "پرداخت کنسل شده اسنپ پی"),
                    ("SU", "سفارش آپدیت شده اسنپ پی"),
                    ("ZC", "سفارش کنسل شده زرین پال"),
                ],
                max_length=5,
                null=True,
                verbose_name="وضعیت",
            ),
        ),
    ]
