# Generated by Django 5.0.7 on 2025-07-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="persian_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="نام فارسی"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("snapppay", "SnappPay"), ("zarinpal", "Zarinpal")],
                default="zarinpal",
                max_length=20,
                verbose_name="روش پرداخت",
            ),
        ),
    ]
