# Generated by Django 5.0.7 on 2025-07-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_category_persian_name_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_discount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
