# Generated by Django 5.0.7 on 2025-07-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_order_order_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="order_item_discount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
