# Generated by Django 5.0.7 on 2025-07-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_orderproduct_order_item_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_discount_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="کدتخفیف سفارش"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="gateway_bank_order_authority",
            field=models.CharField(
                max_length=50, null=True, verbose_name="کد مرجع زرین پال"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="gateway_bank_order_ref_id",
            field=models.BigIntegerField(null=True, verbose_name="کد رهگیری زرین پال"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_discount",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="مجموع کسری کد تخفیف",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="snapppay_payment_token",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="توکن پرداخت اسنپ پی",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="snapppay_transaction_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="کد تراکنش اسنپ پی"
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="order_item_discount",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="کسری کد تخفیف"
            ),
        ),
    ]
