# Generated by Django 5.0 on 2025-11-30 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_order_order_discount_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productsize",
            options={
                "verbose_name": "محصول به تفکیک مشخصه",
                "verbose_name_plural": "محصول به تفکیک مشخصه",
            },
        ),
        migrations.RemoveField(
            model_name="productsize",
            name="height",
        ),
        migrations.RemoveField(
            model_name="productsize",
            name="width",
        ),
        migrations.AddField(
            model_name="productsize",
            name="attribute",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.attribute",
                verbose_name="مشخصه",
            ),
        ),
        migrations.AddField(
            model_name="productsize",
            name="value",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.attributevalue",
                verbose_name="ارزش",
            ),
        ),
        migrations.DeleteModel(
            name="ProductAttributeValue",
        ),
    ]
