# Generated by Django 5.0 on 2025-12-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_productsize_options_remove_productsize_height_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="frame",
        ),
        migrations.RemoveField(
            model_name="product",
            name="glass",
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="secondary_value",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ارزش دوم مشخصه"
            ),
        ),
    ]
