# Generated by Django 5.0 on 2025-12-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_remove_product_color_remove_product_frame_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="shop_produc_content_a2a2d7_idx",
        ),
        migrations.RemoveField(
            model_name="product",
            name="content_code",
        ),
    ]
