# Generated by Django 5.0 on 2025-12-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_remove_product_shop_produc_content_a2a2d7_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsize",
            name="real_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="قیمت به دلار"
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="price",
            field=models.PositiveIntegerField(verbose_name="قیمت به تومان"),
        ),
    ]
