# Generated by Django 5.0 on 2025-12-25 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_productsize_real_price_alter_productsize_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselListng",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="از نوشتن اسامی طولانی خودداری کنید",
                        max_length=255,
                        verbose_name="نام",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="تصویر 384 پیکسل در 384 پیکسل باشد",
                        null=True,
                        upload_to="image/home",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "item_url",
                    models.CharField(
                        help_text="در این قسمت لینک قرار میگیرد و از قرار دادن متن غیر لینک خودداری کنید",
                        max_length=255,
                        verbose_name="لینک",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False,
                        help_text="می توانید وضعیت نمایش را خاموش یا روشن کنید",
                        verbose_name="وضعیت نمایش",
                    ),
                ),
            ],
            options={
                "verbose_name": "کروسل",
                "verbose_name_plural": "کروسل",
            },
        ),
        migrations.CreateModel(
            name="ClassicListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="از نوشتن اسامی طولانی خودداری کنید",
                        max_length=255,
                        verbose_name="نام",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="تصویر 384 پیکسل در 384 پیکسل باشد",
                        null=True,
                        upload_to="image/home",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "item_url",
                    models.CharField(
                        help_text="در این قسمت لینک قرار میگیرد و از قرار دادن متن غیر لینک خودداری کنید",
                        max_length=255,
                        verbose_name="لینک",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False,
                        help_text="می توانید وضعیت نمایش را خاموش یا روشن کنید",
                        verbose_name="وضعیت نمایش",
                    ),
                ),
            ],
            options={
                "verbose_name": "لیست کلاسیک",
                "verbose_name_plural": "لیست کلاسیک",
            },
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="size",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.productsize",
                verbose_name="متغیر",
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="قیمت به تومان"
            ),
        ),
        migrations.CreateModel(
            name="HomeUI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_desktop",
                    models.ImageField(
                        blank=True,
                        help_text="طول: 1920 پیکسل | عرض: 840 پیکسل",
                        null=True,
                        upload_to="image/home",
                        verbose_name="تصویر هدر دسکتاپ",
                    ),
                ),
                (
                    "image_mobile",
                    models.ImageField(
                        blank=True,
                        help_text="طول: 1600 پیکسل | عرض: 1080 پیکسل",
                        null=True,
                        upload_to="image/home",
                        verbose_name="تصویر هدر موبایل",
                    ),
                ),
                (
                    "video_desktop",
                    models.FileField(
                        blank=True,
                        help_text="طول: 1920 پیکسل | عرض: 840 پیکسل",
                        null=True,
                        upload_to="image/home",
                        verbose_name="ویدیو هدر دسکتاپ",
                    ),
                ),
                (
                    "video_mobile",
                    models.FileField(
                        blank=True,
                        help_text="طول: 1600 پیکسل | عرض: 1080 پیکسل",
                        null=True,
                        upload_to="image/home",
                        verbose_name="ویدیو هدر موبایل",
                    ),
                ),
                (
                    "header_url",
                    models.CharField(
                        help_text="در این قسمت لینک قرار میگیرد و از قرار دادن متن غیر لینک خودداری کنید",
                        max_length=255,
                        verbose_name="لینک هدر",
                    ),
                ),
                (
                    "new_products_display",
                    models.BooleanField(
                        default=True, verbose_name="نمایش محصولات جدید"
                    ),
                ),
                (
                    "carousel_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.carousellistng",
                        verbose_name="لیست کروسل",
                    ),
                ),
                (
                    "classic_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.classiclisting",
                        verbose_name="لیست کلاسیک",
                    ),
                ),
            ],
            options={
                "verbose_name": "المان های صفحه اصلی",
                "verbose_name_plural": "المان های صفحه اصلی",
            },
        ),
    ]
