# Generated by Django 5.0 on 2025-12-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_carousellistng_classiclisting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeui",
            name="modified_date",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="تاریخ آخرین تغییر"
            ),
        ),
    ]
