# Generated by Django 5.0 on 2025-12-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_homeui_modified_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homeui",
            name="carousel_listing",
        ),
        migrations.RemoveField(
            model_name="homeui",
            name="classic_listing",
        ),
        migrations.AddField(
            model_name="carousellistng",
            name="home_ui",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="shop.homeui"
            ),
        ),
        migrations.AddField(
            model_name="classiclisting",
            name="home_ui",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="shop.homeui"
            ),
        ),
    ]
