# Generated by Django 5.0 on 2025-12-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_remove_homeui_carousel_listing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classiclisting",
            name="image_two",
            field=models.ImageField(
                blank=True,
                help_text="تصویر 384 پیکسل در 384 پیکسل باشد",
                null=True,
                upload_to="image/home",
                verbose_name="تصویر هاور",
            ),
        ),
    ]
